logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
            nodeValue: INFO
        transaction:
          interceptor: TRACE
          nodeValue: INFO
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.postgresql.Driver
#    username: root
#    password: root
#    url: jdbc:postgresql://client_contacts-db:5432/contacts?encoding=utf8
#    url: jdbc:postgresql://localhost:5432/client-contacts?encoding=utf8
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    url: ${SPRING_DATASOURCE_URL}

  sql:
    init:
      mode: always

server:
  port: '8080'
---
spring:
  datasource:
    driverClassName: org.h2.Driver
    username: test
    password: test
    url: jdbc:h2:mem:contacts
  config:
    activate:
      on-profile: test