-- DROP TABLE IF EXISTS clients CASCADE;
-- DROP TABLE IF EXISTS contacts CASCADE;

CREATE TABLE IF NOT EXISTS clients
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    name  VARCHAR(100) UNIQUE                      NOT NULL,
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS contacts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY          NOT NULL,
    contact_id  BIGINT REFERENCES clients(id) ON DELETE CASCADE  NOT NULL,
    type        SMALLINT                                         NOT NULL,
    description VARCHAR(100) UNIQUE                              NOT NULL,
    CONSTRAINT pk_contacts PRIMARY KEY (id)
);
